config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :eps
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  devise_for :admins
  devise_for :usuarios, controllers: {registrations: 'usuarios/registrations'}
  resources :servicios
  resources :ips
  resources :ips
  resources :ips
  resources :eps
  get 'ips/index'
  root to: "ips#index"

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
    has_and_belongs_to_many :ips, join_table: "servicios_ips"
    accepts_nested_attributes_for :ips
    
    def to_label
        "#{nombre}"
    end
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:nombre)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= simple_form_for(@servicio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editar Servicio</h1>

<%= render 'form' %>

<%= link_to 'Ver', @servicio %> |
<%= link_to 'Atrás', servicios_path %>

app/views/servicios/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3>Servicios</h3></div>

    <table class="table">
    <thead>
        <tr>
        <th>Nombre</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @servicios.each do |servicio| %>
        <tr>
            <td><%= servicio.nombre %></td>
            <td><%= link_to 'Ver', servicio %></td>
            <td><%= link_to 'Editar', edit_servicio_path(servicio) %></td>
            <td><%= link_to 'Eliminar', servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>
<br>

<%= link_to 'Nuevo Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New Servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @servicio.nombre %>
</p>

<%= link_to 'Editar', edit_servicio_path(@servicio) %> |
<%= link_to 'Volver', servicios_path %>