config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :eps
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  devise_for :admins
  devise_for :usuarios, controllers: {registrations: 'usuarios/registrations'}
  resources :servicios
  resources :ips
  resources :ips
  resources :ips
  resources :eps
  get 'ips/index'
  root to: "ips#index"

end

app/models/ep.rb
class Ep < ActiveRecord::Base
    has_and_belongs_to_many :ips
    accepts_nested_attributes_for :ips
    
    def self.options_for_select
      order('LOWER(nombre)').map { |e| [e.nombre, e.id] }
    end
    
    def to_label
        "#{nombre}"
    end
    
end

app/controllers/eps_controller.rb
class EpsController < ApplicationController
  before_action :set_ep, only: [:show, :edit, :update, :destroy]

  # GET /eps
  # GET /eps.json
  def index
    @eps = Ep.all
  end

  # GET /eps/1
  # GET /eps/1.json
  def show
  end

  # GET /eps/new
  def new
    @ep = Ep.new
  end

  # GET /eps/1/edit
  def edit
  end

  # POST /eps
  # POST /eps.json
  def create
    @ep = Ep.new(ep_params)

    respond_to do |format|
      if @ep.save
        format.html { redirect_to @ep, notice: 'Ep was successfully created.' }
        format.json { render :show, status: :created, location: @ep }
      else
        format.html { render :new }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eps/1
  # PATCH/PUT /eps/1.json
  def update
    respond_to do |format|
      if @ep.update(ep_params)
        format.html { redirect_to @ep, notice: 'Ep was successfully updated.' }
        format.json { render :show, status: :ok, location: @ep }
      else
        format.html { render :edit }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eps/1
  # DELETE /eps/1.json
  def destroy
    @ep.destroy
    respond_to do |format|
      format.html { redirect_to eps_url, notice: 'Ep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ep
      @ep = Ep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ep_params
      params.require(:ep).permit(:nombre)
    end
end

app/helpers/e_ps_helper.rb
module EPsHelper
end

app/helpers/eps_helper.rb
module EpsHelper
end

app/views/eps/_form.html.erb
<%= form_for(@ep) do |f| %>
  <% if @ep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ep.errors.count, "error") %> prohibited this ep from being saved:</h2>

      <ul>
      <% @ep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eps/edit.html.erb
<h1>Editar EPS</h1>

<%= render 'form' %>

<%= link_to 'Ver', @ep %> |
<%= link_to 'Volver', eps_path %>

app/views/eps/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3>EPS</h3></div>

    <table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eps.each do |ep| %>
      <tr>
        <td><%= ep.nombre %></td>
        <td><%= link_to 'Ver', ep %></td>
        <td><%= link_to 'Editar', edit_ep_path(ep) %></td>
        <td><%= link_to 'Eliminar', ep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Nueva EPS', new_ep_path %>

app/views/eps/new.html.erb
<h1>Nueva EPS</h1>

<%= render 'form' %>

<%= link_to 'Volver', eps_path %>

app/views/eps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ep.nombre %>
</p>

<%= link_to 'Edit', edit_ep_path(@ep) %> |
<%= link_to 'Back', eps_path %>