config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :eps
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  resources :ips
  devise_for :admins
  devise_for :usuarios, controllers: {registrations: 'usuarios/registrations'}
  resources :servicios
  resources :ips
  resources :ips
  resources :ips
  resources :eps
  get 'ips/index'
  root to: "ips#index"

end

app/models/ip.rb
class Ip < ActiveRecord::Base
    has_and_belongs_to_many :eps, join_table: "eps_ips"
    has_and_belongs_to_many :servicios, join_table: "servicios_ips"
    accepts_nested_attributes_for :eps, :servicios
    filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
      :sorted_by,
      :eps_x,
      :search_query
        ]
     )
   

    scope :sorted_by, lambda { |sort_option|
      direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
      case sort_option.to_s
      when /^created_at_/
        order("ips.created_at #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
      end
    }
  scope :search_query, lambda { |query|
    where("id LIKE ?", "%#{query}%")
  }

 scope :eps_x , lambda { |ep| joins(:eps).where("eps.id = ?", ep) }    

 def self.options_for_sorted_by
    [
     
      ['Registration date (newest first)', 'created_at_desc'],
      ['Registration date (oldest first)', 'created_at_asc'],
     ]
  end
    def to_label
        "#{nombre}"
    end
    
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :set_ip, only: [:show, :edit, :update, :destroy]

  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.order("id DESC")
    if params[:ep_id].present?
      @ips = @ips.joins(:eps).where("ep_id = ?", params[:ep_id])
    end
    if params[:servicio_id].present?
      @ips = @ips.joins(:servicios).where("servicio_id = ?", params[:servicio_id])
    end
  end


  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # GET /ips/1/edit
  def edit
  end
  
  

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(ip_params)

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render :show, status: :created, location: @ip }
      else
        format.html { render :new }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ips/1
  # PATCH/PUT /ips/1.json
  def update
    respond_to do |format|
      if @ip.update(ip_params)
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip }
      else
        format.html { render :edit }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip.destroy
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      @ip = Ip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.require(:ip).permit(:nombre, :longitud, :latitud, :horario_atencion, :direccion, :ep_ids => [], :servicio_ids => [])
    end
    

end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/ips/_form.html.erb
<%= simple_form_for(@ip) do |f| %>
    <% if @ip.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ip.errors.count, "error") %> Crear una IPS:</h2>
          <ul>
          <% @ip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <%= f.input :nombre%>
      <%= f.input :longitud%>
      <%= f.input :latitud%>
      <%= f.input :horario_atencion%>
      <%= f.input :direccion%>
      <%= f.association :eps,  :as => :check_boxes %>
      <%= f.association :servicios,  :as => :check_boxes %>
    
      <%= f.button :submit %>
   
<% end %>

app/views/ips/_list.html.erb
<%# app/views/ips/_list.html.erb %>
<div id="filterrific_results">
<div class="panel panel-default">
  <!-- Default panel contents -->

    <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Horario atencion</th>
        <th>Direccion</th>
      </tr>
    </thead>

    <tbody>
      <% @ips.each do |ip| %>
        <tr>
          <td><%= ip.nombre %></td>
          <td><%= ip.horario_atencion %></td>
          <td><%= ip.direccion %></td>
          <td><%= link_to 'Ver', ip %></td>
          <td><%= link_to 'Editar', edit_ip_path(ip) %></td>
          <td><%= link_to 'Borrar', ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCd8AmZ9AKjXd1EdKQnhtB4WcAudJwMHpg"
  type="text/javascript"></script>
  
  <script src="http://maps.googleapis.com/maps/api/js?libraries=geometry&sensor=false" type="text/javascript"></script>
<script>
    

    
    var myCenter;
    var latitud;
    var longitud;
    var nombre;
    var eps;
    var servicios;
    var direccion;
    var horario;
    
    
    
    
    function localizame() {
            if (navigator.geolocation) { /* Si el navegador tiene geolocalizacion */
                navigator.geolocation.getCurrentPosition(coordenadas);
            }else{
                alert('Oops! Tu navegador no soporta geolocalización. Bájate Chrome, que es gratis!');
            }
        }
        
        function coordenadas(position) {
            latitud = position.coords.latitude; /*Guardamos nuestra latitud*/
            longitud = position.coords.longitude; /*Guardamos nuestra longitud*/
            var minimo = 0;
            var ubicacionUsuario = new google.maps.LatLng(latitud, longitud);
            <% @ips.each do |ip| %>
            var punto = new google.maps.LatLng(<%= ip.latitud %>,<%= ip.longitud %>);
            var distancia = google.maps.geometry.spherical.computeDistanceBetween(ubicacionUsuario, punto); 
            if(minimo == 0){
                minimo = distancia;
            }
            if(distancia < minimo){
                minimo = distancia;
                alert
                nombre = "<%= ip.nombre %>";
                eps = "<%= ip.eps.map {|x| x.to_label}.join ', ' %>";
                servicios = "<%= ip.servicios.map {|x| x.to_label}.join ', ' %>";
                horario = "<%= ip.horario_atencion %>";
                direccion = "<%= ip.direccion %>";
                myCenter = new google.maps.LatLng(<%= ip.latitud %>,<%= ip.longitud %>);
            }
            <% end %>
      
            initialize();
        }
    
    function initialize() {
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        directionsDisplay = new google.maps.DirectionsRenderer(); //directions
    
        var mapProp = {
            center:myCenter,
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };
        
        var infowindow = new google.maps.InfoWindow({
        content: ""+nombre
                    +"<br>"+horario
                    +"<br>"+direccion
                    +"<br><b>EPS</b>"
                    +"<br>"+eps
                    +"<br><b>Servicios</b>"
                    +"<br>"+servicios
        });

        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

        var marker=new google.maps.Marker({
            position:myCenter,
            //animation:google.maps.Animation.BOUNCE,
        });

        marker.setMap(map);
        
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map,marker);
        });
        
        //Marcador de usuario
        var markerUsuario = new google.maps.Marker({
            position: new google.maps.LatLng(latitud,longitud),
            //animation:google.maps.Animation.BOUNCE,
        });
        var infowindowUsuario = new google.maps.InfoWindow({
        content: "tu"
        });
        
        markerUsuario.setMap(map);
        google.maps.event.addListener(markerUsuario, 'click', function() {
            infowindowUsuario.open(map,markerUsuario);
        });
        
        //directions
        
        directionsDisplay.setMap(map);
        directionsDisplay.setPanel(document.getElementById('directions-panel'));
        
        var start = new google.maps.LatLng(latitud,longitud)
        var end = myCenter;
        var request = {
            origin: start,
            destination: end,
            travelMode: google.maps.TravelMode.DRIVING
        };
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
            }
        });
        
    }


    google.maps.event.addDomListener(window, 'load', localizame);
    
    //calcular distancias 
    //http://www.funcion13.com/calculando-distancias-y-areas-con-google-maps-v3/
</script>



<div id="googleMap" style="width:700px;height:600px;"></div>
<div id="directions-panel"></div>

app/views/ips/edit.html.erb
<h1>Editar Ip</h1>

<%= render 'form' %>

<%= link_to 'Ver', @ip %> |
<%= link_to 'Volver', ips_path %>

app/views/ips/index.html.erb
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
</head>

 <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3>IPS</h3></div>


<%= link_to 'Nueva IPS', new_ip_path %>
<h1>IPS</h1>
<%= form_tag ips_path, method: :get do %>
  <div class="form-group">
    <%= select_tag :ep_id, options_from_collection_for_select(Ep.all, "id", "nombre", params[:ep_id]), prompt: "EPS", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= select_tag :servicio_id, options_from_collection_for_select(Servicio.all, "id", "nombre", params[:servicio_id]), prompt: "Servicio", class: "form-control" %>
  </div>
  <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
<% end %>

<%= render(
  partial: 'ips/list',
  locals: { ips: @ips }
) %>
</div>
</div>

app/views/ips/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'ips/list',
    :locals => { :ips => @ips }
  )
) %>
$("#filterrific_results").html("<%= js %>");

app/views/ips/new.html.erb
<h1>Nueva IPS</h1>

<%= render 'form' %>

<%= link_to 'Volver', ips_path %>

app/views/ips/show.html.erb
  
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCd8AmZ9AKjXd1EdKQnhtB4WcAudJwMHpg"
  type="text/javascript"></script>
<script>
    var myCenter=new google.maps.LatLng(<%= @ip.latitud %>,<%= @ip.longitud %>);
    var latitud;
    var longitud;
    
    function localizame() {
            if (navigator.geolocation) { /* Si el navegador tiene geolocalizacion */
                navigator.geolocation.getCurrentPosition(coordenadas);
            }else{
                alert('Oops! Tu navegador no soporta geolocalización. Bájate Chrome, que es gratis!');
            }
        }
        
        function coordenadas(position) {
            latitud = position.coords.latitude; /*Guardamos nuestra latitud*/
            longitud = position.coords.longitude; /*Guardamos nuestra longitud*/
            initialize();
        }
    
    function initialize() {
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        directionsDisplay = new google.maps.DirectionsRenderer(); //directions
    
        var mapProp = {
            center:myCenter,
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };
        
        var infowindow = new google.maps.InfoWindow({
        content: "<%= @ip.nombre %>"
                    +"<br><%= @ip.horario_atencion %>"
                    +"<br><%= @ip.direccion %>"
                    +"<br><b>EPS</b>"
                    +"<br><%= @ip.eps.map {|x| x.to_label}.join ', ' %>"
                    +"<br><b>Servicios</b>"
                    +"<br><%= @ip.servicios.map {|x| x.to_label}.join ', ' %>"
        });

        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

        var marker=new google.maps.Marker({
            position:myCenter,
            //animation:google.maps.Animation.BOUNCE,
        });

        marker.setMap(map);
        
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map,marker);
        });
        
        //Marcador de usuario
        var markerUsuario = new google.maps.Marker({
            position: new google.maps.LatLng(latitud,longitud),
            //animation:google.maps.Animation.BOUNCE,
        });
        var infowindowUsuario = new google.maps.InfoWindow({
        content: "tu"
        });
        
        markerUsuario.setMap(map);
        google.maps.event.addListener(markerUsuario, 'click', function() {
            infowindowUsuario.open(map,markerUsuario);
        });
        
        //directions
        
        directionsDisplay.setMap(map);
        directionsDisplay.setPanel(document.getElementById('directions-panel'));
        
        var start = new google.maps.LatLng(latitud,longitud)
        var end = myCenter;
        var request = {
            origin: start,
            destination: end,
            travelMode: google.maps.TravelMode.DRIVING
        };
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
            }
        });
        
    }


    google.maps.event.addDomListener(window, 'load', localizame);
    
    //calcular distancias 
    //http://www.funcion13.com/calculando-distancias-y-areas-con-google-maps-v3/
</script>



<div id="googleMap" style="width:700px;height:600px;"></div>
<div id="directions-panel"></div>